###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [24]:
import numpy as np
arr=np.random.randint(0,100,12).reshape(4,3)
print(arr)
a=np.sort(arr)
np.random.seed(0)
a

[[44 47 64]
 [67 67  9]
 [83 21 36]
 [87 70 88]]


array([[44, 47, 64],
       [ 9, 67, 67],
       [21, 36, 83],
       [70, 87, 88]], dtype=int32)

In [25]:
sorted_by_col_2=arr[arr[:,1].argsort()]
sorted_by_col_2

array([[83, 21, 36],
       [44, 47, 64],
       [67, 67,  9],
       [87, 70, 88]], dtype=int32)

In [27]:
arr[arr.max(axis=1).argsort()]

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36],
       [87, 70, 88]], dtype=int32)

In [28]:
np.sort(arr,axis=None)

array([ 9, 21, 36, 44, 47, 64, 67, 67, 70, 83, 87, 88], dtype=int32)

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [36]:
marks=np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
print(marks)
extra_subject =np.array([41, 87, 72, 36, 92]).reshape(5,1)
marks=np.hstack((marks,extra_subject))
marks

[[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]]


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [39]:
new_stud1=np.array([77, 83, 98, 95, 89])
new_stud2=np.array([92, 71, 52, 61, 53])
marks=np.vstack((marks,new_stud1,new_stud2))
marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [41]:
total_marks=marks.sum(axis=1).reshape(-1,1)
marks_with_total=np.hstack((marks,total_marks))
marks_with_total

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [42]:
sort=marks_with_total[marks_with_total[:,-1].argsort()[::-1]]
sort

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329],
       [ 63,  46,  90,  42,  87, 328],
       [ 67,  61,  59,  36,  92, 315],
       [ 82,   9,  29,  78,  36, 234],
       [ 39,  76,  13,  29,  72, 229],
       [ 13,  10,   9,  33,  41, 106]])

In [43]:
sort[:2]

array([[ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [50]:
arr = np.array([
    [1, 2, 3, 3, 1, 1],
    [0, 9, 1, 2, 8, 8],
    [1, 2, 3, 8, 8, 8],
    [1, 2, 3, 3, 1, 1]
])
unique_rows=np.unique(arr,axis=0)
unique_cols=np.unique(arr,axis=1)

print("row-wise\n",unique_rows)
print("col-wise\n",unique_cols)

row-wise
 [[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
col-wise
 [[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [60]:
a=np.arange(1,10).reshape(3,3)
print(a)
np.flip(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [62]:
arr =np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
x=6
rows=np.where(np.any(arr>x,axis=1))[0]
rows

array([1, 3])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [64]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [67]:
arr1.flatten()

array([0, 1, 2])

In [69]:
arr2.flatten()

array([3, 4, 5, 6])

In [71]:
arr3.flatten()

array([7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [86]:
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
max=arr.max()
print(max)
min=arr.min()
print(min)
flat=arr.flatten()

filtered = flat[(flat != min) & (flat != max)]
filtered

998
103


array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503, 320,
       230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946, 587,
       227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296, 879,
       575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528, 395,
       525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800, 976,
       786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803, 621,
       453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 194, 76

In [88]:
np.where(filtered==103)

(array([], dtype=int64),)

In [89]:
np.where(filtered==998)

(array([], dtype=int64),)

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [95]:
np.random.seed(42)
arr=np.random.randint(100,700,20)
print(arr)
arr1=np.clip(arr,100,200)
print(arr1)
sorted_arr=np.sort(arr1)
print(sorted_arr)
a=np.cumsum(sorted_arr)
print("cummulative sum\n ",a)

[202 535 370 206 171 120 221 566 314 430 558 187 472 199 230 408 443 591
 513 485]
[200 200 200 200 171 120 200 200 200 200 200 187 200 199 200 200 200 200
 200 200]
[120 171 187 199 200 200 200 200 200 200 200 200 200 200 200 200 200 200
 200 200]
cummulative sum
  [ 120  291  478  677  877 1077 1277 1477 1677 1877 2077 2277 2477 2677
 2877 3077 3277 3477 3677 3877]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [99]:
np.random.seed(10)
arr=np.random.random(20)
print(arr)

arr1=np.round(arr,3)
print(arr1)

p0=np.percentile(arr1,0)
p100=np.percentile(arr1,100)
print(p0,p100,arr1.min(),arr1.max())

p51=np.percentile(arr1,51)
p50=np.percentile(arr1,50)

print(p51,p50)
print(p51-p50)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578]
[0.771 0.021 0.634 0.749 0.499 0.225 0.198 0.761 0.169 0.088 0.685 0.953
 0.004 0.512 0.813 0.613 0.722 0.292 0.918 0.715]
0.004 0.953 0.004 0.953
0.62749 0.6234999999999999
0.003990000000000049
