**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [8]:
vector=np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
vector[4]=1
vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [5]:
import numpy as np
a=int(input("enter a number rows:"))
b=int(input("enter a number column:"))

arr=np.random.rand(a,b)
print('random array:\n',arr)

avg=np.mean(arr)
print('average',avg)

enter a number rows: 3
enter a number column: 4


random array:
 [[0.87938717 0.32090238 0.9607674  0.22173236]
 [0.6710505  0.15768995 0.83647695 0.07611544]
 [0.01030631 0.05065014 0.13897497 0.97463851]]
average 0.44155767442787636


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [35]:
def border_array(a,b):
    arr=np.ones((a,b),dtype=int)
    arr[1:-1,1:-1]=0
    return arr
result=border_array(4,4)
result

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [36]:
arr=np.random.rand(10).reshape(5,2)
arr

array([[0.94922291, 0.01324548],
       [0.72931256, 0.01324577],
       [0.65375544, 0.12285206],
       [0.38251321, 0.91906211],
       [0.62428097, 0.92253525]])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [44]:
# idenity matri
arr=np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [57]:
arr=np.zeros((5,5),dtype=int)
arr1=arr+np.arange(5)
arr1

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [78]:
point=np.array([2,3])

arr=np.random.randint(1,100,20).reshape(10,2)
print('random coordinates\n',arr)

#distance=
distance=np.sqrt(np.sum((arr-point)**2,axis=1))

distance=distance.astype(int)
distance

random coordinates
 [[59 62]
 [44 80]
 [30 25]
 [32  4]
 [15 62]
 [91 46]
 [ 5 25]
 [90 61]
 [52 68]
 [46 99]]


array([ 82,  87,  35,  30,  60,  98,  22, 105,  82, 105])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [87]:
arr=np.arange(0,336).reshape(6,7,8)
print(arr)
index=np.unravel_index(100,arr.shape)
print("index of 100th element is:",index)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [97]:
arr=np.array(input("enter space separated numbers:").split(),float)
arr1=arr[::-1]
print(arr1)

enter space separated numbers: 1 2 3 4 -8 -10


[-10.  -8.   4.   3.   2.   1.]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [105]:
#example 1:-
arr=np.array([])
arr1=np.array([1,2])
len(arr),len(arr1)

(0, 2)

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [115]:
def softmax(x):
    exp_x=np.exp(x)
    summ=np.sum(exp_x)
    return exp_x/summ

arr1=np.array([86.03331084, 37.7285648,  48.64908087, 87.16563062, 38.40852563, 37.20006318])
arr2=np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098 , 68.82830233 ,91.52064278])

result1=softmax(arr1)
print(result1)
print("###################################################")
result2=softmax(arr2)
print(result2)

    #Code here

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]
###################################################
[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [131]:
def stack():
    a=np.array([[0, 1, 2, 3, 4],
                [5, 6 ,7, 8, 9]])

    b=np.array([[1, 1, 1, 1, 1],
                [1 ,1 ,1, 1, 1]])

    return np.vstack((a,b))
stack()

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [136]:
def stack1():
    a=np.array([[0, 1, 2, 3, 4],
                [5, 6 ,7, 8, 9]])

    b=np.array([[1, 1, 1, 1, 1],
                [1, 1, 1, 1 ,1]])

    c=np.array([[0.10117373, 0.1677244,  0.73764059, 0.83166097, 0.48985695],
                [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])
    return np.vstack([a,b,c])
stack1()

array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.10117373, 0.1677244 , 0.73764059, 0.83166097, 0.48985695],
       [0.44581567, 0.13502419, 0.55692335, 0.16479622, 0.61193593]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [143]:
def date_array(start, end):
    if not (isinstance(start, str) and isinstance(end, str)):
        raise TypeError("Both start and end dates must be strings")

    return np.arange(np.datetime64(start), np.datetime64(end) + np.timedelta64(1, 'D')).astype(str)
a=date_array( '2020-09-15','2020-09-25')
b=date_array('2022-12-01','2022-12-06')
c=date_array('2020-11-25','2020-11-30')
print(a)
print(b)
print(c)

['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']
['2022-12-01' '2022-12-02' '2022-12-03' '2022-12-04' '2022-12-05'
 '2022-12-06']
['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [157]:
arr1=np.arange(0,6).reshape(2,3)
print(arr1)
row_mean=arr1.mean(axis=1)
print(row_mean)
result=arr1-arr1.mean(axis=1,keepdims=True)
result

#result

[[0 1 2]
 [3 4 5]]
[1. 4.]


array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [164]:
arr1=np.arange(1,10).reshape(3,3)
print(arr1)
arr1[:,[0,1]]=arr1[:,[1,0]]
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 3]
 [5 4 6]
 [8 7 9]]


###`Q-16:` Replace odd elements in arrays with -1.

In [165]:
arr1

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [177]:
arr1=np.arange(1,10).reshape(3,3)
print(arr1)
arr1[arr1 %2 !=0]=-1
arr1

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[-1,  2, -1],
       [ 4, -1,  6],
       [-1,  8, -1]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [185]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=np.vstack((a,b))
np.max(c,axis=0)


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [ ]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[2939, 1694, 6680, 8865, 2684],
       [4066, 4573,  327, 6525,  851],
       [5997, 7481, 2315, 5863, 9615],
       [7821, 1225, 9138, 1114, 4885],
       [7715, 8046, 9105, 3935, 3182],
       [8842, 4836, 2705, 3751, 3800],
       [4132, 1400, 7844, 9471, 7526],
       [2749, 2624, 6900, 1576, 7515]])

In [187]:
normalized = (arr1 - arr1.min()) / (arr1.max() - arr1.min())
normalized

array([[0.        , 0.33333333, 0.        ],
       [0.55555556, 0.        , 0.77777778],
       [0.        , 1.        , 0.        ]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [188]:
def largest(arr,n):
    arr=np.sort(arr)
    return arr[-n]
arr=np.array([12,34,40,7,1,0])
print('3rd largest:',largest(arr,3))
print('1st largest:',largest(arr,1))

3rd largest: 12
1st largest: 40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [192]:
#code here
a=np.array([1,2,3])
a1=np.repeat(a,3)
a2=np.tile(a,3)
result=np.concatenate([a1,a2])
result

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

# Step 1️⃣: Repeat each element 3 times → [1 1 1 2 2 2 3 3 3]
part1 = np.repeat(a, 3)

# Step 2️⃣: Repeat full array 3 times → [1 2 3 1 2 3 1 2 3]
part2 = np.tile(a, 3)

# Step 3️⃣: Combine both parts
result = np.concatenate([part1, part2])
print(result)
